name: Deploy

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > newkey.pem
        chmod 600 newkey.pem
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -t -i "newkey.pem" ubuntu@ec2-13-233-154-44.ap-south-1.compute.amazonaws.com "sudo bash ~/deploy.sh"

ssh -i "newkey.pem" ubuntu@ec2-13-233-154-44.ap-south-1.compute.amazonaws.com